spring:
  application:
    name: demo-ai
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
#        model: deepseek-r1:7b
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.zz.demoai: debug