spring:
  application:
    name: demo-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
#        model: deepseek-r1:7b
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.zz.demoai: debug